version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_MODELS=${OLLAMA_MODEL}
    command: >
      sh -c "ollama run ${OLLAMA_MODEL} && tail -f /dev/null"

volumes:
  mongo-data:
  ollama-data:
